In [39]:
import save as sv 
import pandas as pd
import numpy as np

In [40]:
series = sv.lectureFichier("./serie")

In [41]:
series[1]

['dance academy ',
 'night gallery ',
 'apocalypse the second world war ',
 'the street ',
 'eternal law ',
 'dexter s laboratory ',
 'carlos ',
 'good vibes ',
 'bbc seven ages of britain ',
 'open all hours ',
 'my babysitter s a vampire ',
 'prisoners wives ',
 'the rockford files ',
 '49 days ',
 'the playboy club ',
 'blue murder uk ',
 'man from atlantis ',
 'jem ',
 'kodenavn hunter ',
 'mad dogs ',
 'how do you want me ',
 'three inches ',
 'dating rules from my future self ',
 'danger 5 ',
 'how to rock ',
 'almost heroes ',
 'ultraman nexus ',
 'martina cole s the runaway ',
 'superjail ',
 'operation good guys ',
 'the body farm ',
 'stella uk ',
 'white heat ',
 'justice 2011 ',
 'the story of musicals ',
 'stark raving mad ',
 'america s next great restaurant ',
 'death valley ',
 'white van man ',
 'the caf ',
 '1066 the battle for middle earth ',
 'neverland ',
 'trollied ',
 'person of interest ',
 '2 broke girls ',
 'unforgettable ',
 'watson oliver ',
 'the invisible man 2000 ',
 'extreme makeover weight loss edition ',
 'the secret circle ',
 'queen days of our lives ',
 'q viva the chosen ',
 'karabudjan ',
 'the thorn birds ',
 'wonders of the universe ',
 'big train ',
 'rescue special ops ',
 'last man standing ',
 'wild boys ',
 'knight rider 1982 ',
 'two guys and a girl ',
 'gormenghast ',
 'dr quinn medicine woman ',
 'the cousteau odyssey ',
 'ornen en krimi odysse ',
 'spongebob squarepants ',
 'morden i sandhamn murders in sandhamn ',
 'the fades ',
 'less than kind ',
 'a history of horror with mark gatiss bbc ',
 'charlie s angels 1976 ',
 'il capo dei capi ',
 'mission impossible 1966 ',
 'lilyhammer ',
 'f troop ',
 'aqua teen hunger force ',
 'moonlighting ',
 'dalziel and pascoe ',
 'the x factor us ',
 'angry boys ',
 'engrenages ',
 'inside nature s giants ',
 'dark skies ',
 'the walking dead webisodes ',
 'smash ',
 'gcb ',
 'top chef masters ',
 'bbc men of rock ',
 'without you ',
 'catterick ',
 'the protector ',
 'p90x ',
 'redemption inc ',
 'rumpole of the bailey ',
 'baywatch ',
 'new girl ',
 'i claudius ',
 'american horror story ',
 'third watch ',
 'breakout kings ',
 'cloudstreet ',
 'boss ',
 'friday night dinner ',
 'you deserve it ',
 'the agatha christie hour ',
 'king 2011 ',
 'dark matters twisted but true ',
 'cracker uk ',
 'kenan kel ',
 'the pranker ',
 'ellery queen ',
 'h8r ',
 'crownies ',
 'hyperdrive ',
 'rush 2008 ',
 'when we left earth the nasa missions ',
 'free agents us ',
 'fear factor us ',
 'reno 911 ',
 'the straits ',
 'falling skies ',
 'the borgias ',
 'doctor who confidential ',
 'danny phantom ',
 'return to eden ',
 'the looney tunes show 2011 ',
 'hammer house of horror ',
 'goosebumps ',
 'death in paradise ',
 'growing pains us ',
 'sapphire steel ',
 'the river ',
 'girl number 9 ',
 'a n t farm ',
 'byzantium the lost empire ',
 'party of five ',
 'legend quest ',
 'teen titans ',
 'bbc power of art ',
 'brave new world with stephen hawking ',
 'leonardo ',
 'war and remembrance ',
 'mad love ',
 'laid ',
 'how sex works ',
 'planet dinosaur ',
 'shogun ',
 'campus ',
 'co ed confidential ',
 'two pints of lager and a packet of crisps ',
 'love bites ',
 'supernatural the animation ',
 'the nostalgia critic ',
 'transformers ',
 'marcel s quantum kitchen ',
 'after the runway ',
 'the truth about lions ',
 'bucket skinner s epic adventures ',
 'nostradamus effect ',
 'switched at birth ',
 'silk ',
 'the comic strip presents ',
 'xiii the series ',
 'chaos ',
 'dynasty ',
 'the ones ',
 'hippies ',
 'green lantern the animated series ',
 'suits ',
 'the magician s house ',
 'raymond blanc the very hungry frenchman ',
 'richard hammond s engineering connections ',
 'batman the animated series ',
 'i just want my pants back ',
 'the royal bodyguard ',
 'coming of age uk ',
 'the code ',
 'missing 2012 ',
 'the exes ',
 'public enemies ',
 'shrek the halls ',
 'suburgatory ',
 'thomas the tank engine friends ',
 'the night watch ',
 'buck rogers in the 25th century ',
 'the field of blood ',
 'the armando iannucci shows ',
 'the nine lives of chloe king ',
 'battleground ',
 '6degrees ',
 'the british at work ',
 'monday monday ',
 'fry s planet word ',
 'so random ',
 'south riding ',
 'the voice ',
 'mrs brown s boys ',
 'king george and queen mary the royals who rescued the monarchy ',
 'wild west ',
 'ultraman max ',
 'andy richter controls the universe ',
 'bible s buried secrets bbc ',
 'the honeymooners ',
 'doctor who night and the doctor ',
 'top boy ',
 'necessary roughness ',
 'jessie 2011 ',
 'ijon tichy raumpilot ',
 'next world ',
 'case histories ',
 'hit the road jack ',
 'bbc the frankincense trail ',
 'hart to hart ',
 'prime suspect ',
 'lost in space ',
 'bent ',
 'ringer ',
 'columbo ',
 'spy 2011 ',
 'el barco ',
 'kolchak the night stalker ',
 'case sensitive ',
 '3rd rock from the sun ',
 'the mystery of edwin drood ',
 'just henry ',
 'the 10th kingdom ',
 'divine ',
 'made in britain ',
 'bbc versailles ',
 'birdsong ',
 'mildred pierce ',
 'buried treasure ',
 'murder rooms the dark beginnings of sherlock holmes ',
 'bbc guilty pleasures ',
 'house of lies ',
 'my little pony friendship is magic ',
 'lovely complex ',
 'kojak 1973 ',
 'hacks ',
 'bbc lost land of the volcano ',
 'american gothic ',
 'bar karma ',
 'exile ',
 'the lying game ',
 'in the wild ',
 'radio free roscoe ',
 'braquo ',
 'city hunter 2010 ',
 'a lonely place for dying ',
 'bomb girls ',
 'life s too short ',
 '10 o clock live ',
 'borgia ',
 'rawhide ',
 'moon machines ',
 'torchwood web of lies ',
 'bonanza ',
 'brimstone ',
 'a history of ancient britain bbc ',
 'the wild wild west ',
 'dungeons dragons ',
 'arctic air ',
 'rollin with zach ',
 'befriend and betray ',
 'kung fu panda legends of awesomeness ',
 'inside the human body ',
 'mortal kombat legacy ',
 'fantastic four ',
 'beaver falls ',
 'thunderbirds ',
 'national geographic extreme universe ',
 'lab rats us ',
 'the bleak old shop of stuff ',
 'fashion star ',
 'bag of bones ',
 'coach ',
 'origins of us ',
 'chemistry ',
 'kaboul kitchen ',
 'bbc planet of the apemen battle for earth ',
 'the story of ireland ',
 'the finder ',
 'man up ',
 'gilligan s island ',
 'comic book men ',
 'daniel boone 1964 ',
 'casualty ',
 'taggart ',
 'cidade dos homens ',
 'burnistoun ',
 'family ties ',
 'earthflight ',
 'luck ',
 'the twilight zone 1985 ',
 'walker texas ranger ',
 'touched by an angel ',
 'the paul reiser show ',
 'friends with benefits ',
 'land of the giants ',
 'against the wall ',
 'the invaders ',
 'the persuaders ',
 'awake ',
 'bad universe ',
 'angel o demonio ',
 'ace lightning ',
 'injustice ',
 'great migrations ',
 'bbc how to build a human ',
 'ultraseven evolution ',
 'thundercats ',
 'cape wrath ',
 'lead balloon ',
 'phoneshop ',
 'project runway all stars ',
 'wilfred us ',
 'the shadow line ',
 'visionaries knights of the magical light ',
 'work of art the next great artist ',
 'london s burning ',
 'the batman ',
 'hiccups ',
 'the firm ',
 're modeled 2012 ',
 'scooby doo where are you ',
 'the cosby show ',
 'wikileaks the secret life of a superpower ',
 'outnumbered ',
 'monroe ',
 'bbc how to grow a planet ',
 'roots us ',
 'bbc the spice trail ',
 'pramface ',
 'bbc penguin island ',
 'the reckoning ',
 'a history of scotland ',
 'star trek ',
 'the muppet show ',
 'ironside ',
 'get smart 1965 ',
 'terra nova ',
 'oceans ',
 'the fantastic four 1994 ',
 'treasure island ',
 'roger and val have just got in ',
 'happy endings ',
 'twentysomething ',
 'alcatraz ',
 'bbc lost land of the jaguar ',
 'the adventures of the galaxy rangers ',
 'den som dr ber ',
 'bbc panorama ',
 'don t trust the b in apartment 23 ',
 'whitney ',
 'twenty twelve ',
 'benidorm ',
 'fortier ',
 'jane by design ',
 'hart of dixie ',
 'the smurfs ',
 'perils of penelope pitstop ',
 'heavy ',
 'transformers animated ',
 'torchwood declassified ',
 'full house us ',
 'franklin bash ',
 'mtvs downtown ',
 'femme fatales ',
 'pawn stars ',
 'the hour ',
 'beavis and butt head ',
 'britain s secret seas ',
 'remington steele ',
 'transformers the headmasters ',
 'on the air uk ',
 'the jury 2011 ',
 'alphas ',
 'ufo ',
 'vera ',
 'eleventh hour uk ',
 'endgame ',
 'connections ',
 'great expectations 2011 ',
 'monty python s personal best ',
 'wings ',
 'love in the wild ',
 'frozen planet ',
 'the promise ',
 'thundercats 2011 ',
 'expedition impossible ',
 'supah ninjas ',
 'the real hustle us ',
 'jean claude van damme behind closed doors ',
 'this is jinsy ',
 'power rangers samurai ',
 'aristocrats ',
 'the girl from tomorrow ',
 'the confession ',
 'mongrels ',
 'transformers prime ',
 'project runway all stars after the runway ',
 'atlantis ',
 'airwolf ',
 'women in love ',
 'murphy s law ',
 'street fighter ii v ',
 'irt deadliest roads ',
 'riddles of the bible ',
 'jackie chan adventures ',
 'sign 2011 ',
 'sirens uk ',
 'the indian doctor ',
 'milton jones s house of rooms ',
 '7th heaven ',
 'son of the beach ',
 'quatermass ii ',
 'the sins ',
 'the tick 1994 ',
 'the glee project ',
 'dark shadows the revival 1991 ',
 'living in your car ',
 'commander in chief ',
 'rejseholdet unit one ',
 'who s still standing ',
 'pan am ',
 'camelot ',
 'revenge ',
 'angels in america ',
 'all in the family ',
 'endeavour ',
 'aeon flux ',
 'known universe ',
 'voyage to the bottom of the sea ',
 'frontline medicine ',
 'bbc the death of yugoslavia ',
 'the slap ',
 'breaking in ',
 'enlightened ',
 'the streets of san francisco ',
 '15 storeys high ',
 'nature s great events ',
 'face off ',
 'thor loki blood brothers ',
 'underwater universe ',
 '101 ways to leave a game show ',
 'jeeves and wooster ',
 'max paddy s road to nowhere ',
 'wolverine ',
 'bedlam ',
 'geordie shore ',
 'off limits ',
 'iron man jp ',
 'in with the flynns ',
 'the crimson petal and the white ',
 'bbc ray mears goes walkabout ',
 'united ',
 'gargoyles ',
 'mobbed ',
 'fast and loose ',
 'america in primetime ',
 'duts ',
 'il commissario montalbano ',
 'titus ',
 'the kennedys ',
 'the dog whisperer ',
 'becoming human ',
 'allen gregory ',
 'the sarah millican television programme ',
 'single white spenny ',
 'our mutual friend ',
 'the hitch hikers guide to the galaxy ',
 'iron man 2011 ',
 'the voice uk ',
 'hotter than my daughter ',
 'bbc lost land of the tiger ',
 'noel fielding s luxury comedy ',
 '32 brinkburn street ',
 'brad meltzer s decoded ',
 'criminal minds suspect behavior ',
 'once upon a time ',
 'spider man the animated series ',
 'the chris rock show ',
 'candy cabs ',
 'the legend of korra ',
 'the mercury men ',
 'teen wolf ',
 'the resistance ',
 'trailer park boys ',
 'homeland ',
 'woodley ',
 'sugartown ',
 'the flintstones ',
 'black mirror 2011 ',
 'awkward ',
 'i hate my teenage daughter ',
 'rab c nesbitt ',
 'stevie tv ',
 'hamarinn the cliff ',
 'appropriate adult ',
 'wolverine us ',
 'outcasts ',
 'damo ',
 'stewart lee s comedy vehicle ',
 'hidden ',
 'bbc shock and awe the story of electricity ',
 'spirited ',
 'riese kingdom falling ',
 'web therapy ',
 'starsky hutch ',
 'austin ally ',
 'state of georgia ',
 'space precinct ',
 'baretta ',
 'dirk gently ',
 'charlie s angels ',
 'miss fisher s murder mysteries ',
 'hunter uk ',
 'last of the summer wine ',
 'land of the lost 1974 ',
 'single ladies ',
 'the guardian ',
 'call the midwife ',
 'rob ',
 'freddy s nightmares ',
 'the six million dollar man ',
 'squidbillies ',
 'happily divorced ',
 'titanic 2012 ',
 'ducktales ',
 'unsupervised ',
 'work it ',
 'crime squad ',
 'bbc secret of the sexes ',
 'young herriot ',
 'grimm ',
 'the l a complex ',
 'blake s 7 ',
 'a gifted man ',
 'combat hospital ',
 'my girlfriend is a gumiho ',
 'mount pleasant ',
 'hell on wheels ',
 'urban legends ',
 'inside men ',
 'the sing off ',
 'the waltons ',
 'slings and arrows ',
 'napoleon dynamite ',
 'zenith ',
 'the yard ',
 'surface ',
 'east west 101 ',
 'marvel knights black panther ',
 'edderkoppen ',
 'bbc everything and nothing ',
 'centennial ',
 'x men jp ',
 'are you there chelsea ',
 'chips ',
 'orbit earth s extraordinary journey ',
 'the life of muhammad ',
 'l5 the series ',
 'life with louie ',
 'cadfael ',
 'blade jp ',
 'odyssey 5 ',
 'touch ',
 'key peele ',
 'the big valley ',
 'catweazle ',
 'bbc the chinese are coming ',
 'wild at heart ',
 'scott and bailey ',
 'real humans kta m nniskor ',
 'get smart 1995 ',
 'logan s run ',
 'up all night ',
 'toledo cruce de destinos ',
 'taxi ',
 'pete versus life ',
 'ultraseven x ',
 'the young ones ',
 'ntsf sd suv ',
 'kickin it ',
 'educating essex ',
 'reunion ',
 'how to be a gentleman ',
 'paradise ranch ',
 'profiler ',
 'jamie oliver s food revolution ',
 'hercules the legendary journeys ',
 'madagascar ',
 'fresh meat ',
 'the bold and the beautiful ',
 'afghanistan bbc ',
 'smiley s people ',
 'freaky eaters ',
 'workaholics ',
 'love life ',
 'talking dead ']

In [42]:
for i in range(len(series[1])):
    series[1][i]=series[1][i].strip()

In [43]:
series[1][10]

'my babysitter s a vampire'

In [44]:
base = sv.lectureFichier("./base_de_donnees")

In [45]:
base

                   reviewer             movie rating  global rating   genre
0                nadyaruray           kingdom      6           4.25  action
1                nadyaruray           kingdom      6           4.15   drama
2                nadyaruray           kingdom      6           2.90   drama
3                nadyaruray           kingdom      6           2.80  action
4             redhawk-70707           kingdom      5           4.25  action
...                     ...               ...    ...            ...     ...
262270         ianlouisiana       in the club      4           2.30   drama
262271         hillrosemary       in the club      9           2.30   drama
262272        Sunshine_pink       in the club      1           2.30   drama
262273          darshangood  pete versus life     10           1.85  comedy
262274  hashtagtechnobabble       newsreaders     10           2.40  comedy

[262275 rows x 5 columns]

In [46]:
len(base['genre'].unique())

12

In [47]:
base = base.drop(columns=['reviewer','rating','global rating'])

In [48]:
base

                   movie   genre
0                kingdom  action
1                kingdom   drama
2                kingdom   drama
3                kingdom  action
4                kingdom  action
...                  ...     ...
262270       in the club   drama
262271       in the club   drama
262272       in the club   drama
262273  pete versus life  comedy
262274       newsreaders  comedy

[262275 rows x 2 columns]

In [49]:
base["subtitles"] = np.nan

In [50]:
base

                   movie   genre  subtitles
0                kingdom  action        NaN
1                kingdom   drama        NaN
2                kingdom   drama        NaN
3                kingdom  action        NaN
4                kingdom  action        NaN
...                  ...     ...        ...
262270       in the club   drama        NaN
262271       in the club   drama        NaN
262272       in the club   drama        NaN
262273  pete versus life  comedy        NaN
262274       newsreaders  comedy        NaN

[262275 rows x 3 columns]

In [51]:
base=base.drop_duplicates('movie')

In [52]:
base

                     movie        genre  subtitles
0                  kingdom       action        NaN
3368     the invisible man       comedy        NaN
3728        rick and morty    animation        NaN
4279             offspring        drama        NaN
4385      call the midwife        drama        NaN
...                    ...          ...        ...
262265       titan maximum    animation        NaN
262266  ancient impossible  documentary        NaN
262269         in the club        drama        NaN
262273    pete versus life       comedy        NaN
262274         newsreaders       comedy        NaN

[1580 rows x 3 columns]

In [53]:
base['movie'][3368]

'the invisible man'

In [54]:
base=base.reset_index()

In [55]:
base

       index               movie        genre  subtitles
0          0             kingdom       action        NaN
1       3368   the invisible man       comedy        NaN
2       3728      rick and morty    animation        NaN
3       4279           offspring        drama        NaN
4       4385    call the midwife        drama        NaN
...      ...                 ...          ...        ...
1575  262265       titan maximum    animation        NaN
1576  262266  ancient impossible  documentary        NaN
1577  262269         in the club        drama        NaN
1578  262273    pete versus life       comedy        NaN
1579  262274         newsreaders       comedy        NaN

[1580 rows x 4 columns]

In [56]:
base = base.drop(columns=['index'])

In [57]:
base

                   movie        genre  subtitles
0                kingdom       action        NaN
1      the invisible man       comedy        NaN
2         rick and morty    animation        NaN
3              offspring        drama        NaN
4       call the midwife        drama        NaN
...                  ...          ...        ...
1575       titan maximum    animation        NaN
1576  ancient impossible  documentary        NaN
1577         in the club        drama        NaN
1578    pete versus life       comedy        NaN
1579         newsreaders       comedy        NaN

[1580 rows x 3 columns]

In [65]:
len(base['movie'])

1580

In [66]:
len(base['subtitles'])

1580

In [67]:
len(series[1])

600

In [68]:
len(series[0])

600

In [69]:
series[0][500][0][0]

['species',
 'like',
 'kill',
 'talk',
 'want',
 'killed',
 'children',
 'virus',
 'c',
 'really',
 'believe',
 'host',
 'force',
 'try',
 'communicate',
 'need',
 'make',
 'use',
 'ac',
 'friend',
 'tate',
 'wants',
 'us',
 'release',
 'want',
 'think',
 'time',
 'start',
 'felt',
 'right',
 'tom',
 'starling',
 'tell',
 'fleur',
 'please',
 'please',
 'beautiful',
 'girl',
 'city',
 'go',
 'back',
 'place',
 'peoples',
 'threatened',
 'complete',
 'annihilation',
 'richard',
 'alchemist',
 'omega',
 'report',
 'requested',
 'hot',
 'worry',
 'tell',
 'anyone',
 'let',
 'know',
 'want',
 'sometime',
 'yeah',
 'cass',
 'find',
 'tipper',
 'please',
 'ask',
 'come',
 'tipper',
 'stella',
 'wants',
 'see',
 'wake',
 'boyfriend',
 'boyfriend',
 'mum',
 'much',
 'morning',
 'person',
 'either',
 'tipper',
 'great',
 'mood',
 'meself',
 'make',
 'drag',
 'sorry',
 'arse',
 'bed',
 'tipper',
 'isolation',
 'ward',
 'tests',
 'light',
 'head',
 'exactly',
 'c',
 'god',
 'giving',
 'antivirals',
 'work',
 'though',
 'viruses',
 'caused',
 'host',
 'force',
 'harm',
 'seen',
 'nothing',
 'c',
 'stopped',
 'last',
 'time',
 'maybe',
 'one',
 'maybe',
 'know',
 'aim',
 'though',
 'heard',
 'fleur',
 'could',
 'send',
 'lily',
 'home',
 'shut',
 'public',
 'places',
 'schools',
 'let',
 'hold',
 'know',
 'exactly',
 'going',
 'need',
 'keep',
 'cool',
 'look',
 'sorry',
 'everything',
 'lies',
 'nothing',
 'thought',
 'yeah',
 'get',
 'apologising',
 'stuff',
 'happened',
 'stuff',
 'completely',
 'business',
 'cass',
 'last',
 'night',
 'got',
 'drunk',
 'slept',
 'jack',
 'probably',
 'finest',
 'hour',
 'either',
 'deal',
 'listen',
 'must',
 'caused',
 'acs',
 'reappear',
 'get',
 'viruses',
 'one',
 'case',
 'diagnosis',
 'yet',
 'harboured',
 'virus',
 'caused',
 'last',
 'plague',
 'use',
 'biblical',
 'terminology',
 'acs',
 'tested',
 'positive',
 'cause',
 'know',
 'listen',
 'nine',
 'years',
 'ago',
 'ordered',
 'shot',
 'last',
 'good',
 'decision',
 'made',
 'one',
 'lynched',
 'bad',
 'decision',
 'julius',
 'hope',
 'suggesting',
 'suggesting',
 'explicitly',
 'accusing',
 'slander',
 'position',
 'take',
 'moral',
 'high',
 'ground',
 'helping',
 'acs',
 'causing',
 'know',
 'possible',
 'alternatives',
 'working',
 'short',
 'burst',
 'static',
 'radio',
 'go',
 'ahead',
 'new',
 'viral',
 'case',
 'sir',
 'lt',
 'callaghan',
 'one',
 'guys',
 'got',
 'well',
 'callaghan',
 'one',
 'interrogated',
 'captured',
 'ac',
 'going',
 'medicentre',
 'monitor',
 'beeps',
 'help',
 'stella',
 'condition',
 'pre',
 'symptomatic',
 'stage',
 'although',
 'raging',
 'thirst',
 'associated',
 'last',
 'outbreak',
 'starting',
 'c',
 'know',
 'yet',
 'different',
 'molecular',
 'structure',
 'calling',
 'c',
 'seems',
 'logical',
 'condition',
 'xp',
 'isolation',
 'unit',
 'worsening',
 'rapidly',
 'progressing',
 'much',
 'faster',
 'rate',
 'progressing',
 'internal',
 'organs',
 'effectively',
 'devouring',
 'know',
 'much',
 'longer',
 'survive',
 'life',
 'expectancy',
 'advanced',
 'c',
 'three',
 'four',
 'days',
 'berger',
 'alchemist',
 'ct',
 'health',
 'crisis',
 'use',
 'advantage',
 'people',
 'handling',
 'parameter',
 'coordinates',
 'entry',
 'interface',
 'landing',
 'beacon',
 'lock',
 'gated',
 'thermal',
 'shields',
 'reveal',
 'contents',
 'omega',
 'file',
 'finally',
 'turn',
 'population',
 'tate',
 'going',
 'man',
 'getting',
 'worse',
 'er',
 'worried',
 'anything',
 'else',
 'reaction',
 'tate',
 'talking',
 'back',
 'killing',
 'ac',
 'prisoner',
 'good',
 'well',
 'issue',
 'kidding',
 'security',
 'issue',
 'holding',
 'till',
 'right',
 'time',
 'considering',
 'latest',
 'developments',
 'rather',
 'pressing',
 'want',
 'look',
 'sorry',
 'mate',
 'flesh',
 'weak',
 'let',
 'face',
 'nothing',
 'important',
 'jack',
 'ever',
 'heard',
 'omega',
 'project',
 'come',
 'attention',
 'recently',
 'confident',
 'hear',
 'say',
 'agree',
 'must',
 'act',
 'quickly',
 'well',
 'word',
 'everyone',
 'staying',
 'indoors',
 'seen',
 'lily',
 'yet',
 'yet',
 'exposed',
 'anyway',
 'thanks',
 'really',
 'reassuring',
 'directly',
 'contagious',
 'else',
 'could',
 'know',
 'yet',
 'proceed',
 'regular',
 'health',
 'issue',
 'people',
 'blame',
 'acs',
 'berger',
 'congregation',
 'hard',
 'work',
 'speak',
 'caused',
 'something',
 'else',
 'people',
 'prefer',
 'easy',
 'lies',
 'difficult',
 'truths',
 'say',
 'nothing',
 'believe',
 'berger',
 'go',
 'know',
 'truth',
 'cos',
 'truth',
 'might',
 'terrifying',
 'close',
 'public',
 'spaces',
 'stay',
 'calm',
 'sorry',
 'closing',
 'public',
 'places',
 'due',
 'health',
 'alert',
 'precaution',
 'probably',
 'reopen',
 'tomorrow',
 'stock',
 'water',
 'keep',
 'watching',
 'bulletins',
 'stock',
 'water',
 'probably',
 'say',
 'every',
 'crisis',
 'maybe',
 'sinking',
 'ship',
 'guess',
 'earlier',
 'said',
 'bit',
 'quite',
 'tired',
 'well',
 'busy',
 'night',
 'meant',
 'sound',
 'dunno',
 'ok',
 'whoa',
 'whoa',
 'whoa',
 'whoa',
 'whoa',
 'whoa',
 'whoa',
 'easy',
 'whoa',
 'walk',
 'walk',
 'stella',
 'going',
 'xps',
 'arrested',
 'fleur',
 'jack',
 'jack',
 'tell',
 'authority',
 'arrest',
 'jack',
 'oh',
 'great',
 'happened',
 'beautiful',
 'woman',
 'city',
 'jack',
 'shag',
 'em',
 'evening',
 'arrest',
 'em',
 'morning',
 'idea',
 'romance',
 'man',
 'sniggers',
 'worry',
 'getting',
 'lot',
 'detail',
 'tell',
 'going',
 'told',
 'get',
 'office',
 'tell',
 'jack',
 'set',
 'free',
 'promise',
 'hell',
 'going',
 'like',
 'review',
 'privileged',
 'file',
 'interested',
 'talking',
 'illegal',
 'detention',
 'fleur',
 'morgan',
 'xps',
 'relating',
 'omega',
 'project',
 'case',
 'reference',
 'officer',
 'perfectly',
 'safe',
 'xp',
 'base',
 'file',
 'concerns',
 'detention',
 'authorised',
 'oh',
 'authorised',
 'council',
 'member',
 'justice',
 'also',
 'demands',
 'see',
 'file',
 'stella',
 'richard',
 'disaster',
 'especially',
 'going',
 'job',
 'stand',
 'boss',
 'secrets',
 'lies',
 'direct',
 'threat',
 'security',
 'claim',
 'responsibility',
 'hand',
 'file',
 'arrest',
 'yes',
 'getting',
 'break',
 'law',
 'help',
 'fleur',
 'get',
 'file',
 'let',
 'us',
 'bring',
 'fleur',
 'pas',
 'course',
 'jack',
 'jack',
 'fast',
 'mocking',
 'jibe',
 'huh',
 'richard',
 'get',
 'want',
 'want',
 'talking',
 'reverence',
 'sessions',
 'schools',
 'persecuting',
 'acs',
 'think',
 'want',
 'know',
 'tell',
 'sighs',
 'place',
 'represents',
 'last',
 'hope',
 'mankind',
 'aware',
 'created',
 'arrive',
 'look',
 'around',
 'think',
 'think',
 'ambition',
 'small',
 'frayed',
 'edges',
 'frayed',
 'edges',
 'know',
 'actually',
 'well',
 'say',
 'ambitions',
 'small',
 'inter',
 'continental',
 'ballistic',
 'missile',
 'tall',
 'gleaming',
 'almost',
 'noble',
 'perfectly',
 'designed',
 'purpose',
 'packed',
 'uranium',
 'filled',
 'deadly',
 'ambition',
 'nothing',
 'frayed',
 'edges',
 'one',
 'city',
 'another',
 'across',
 'oceans',
 'mountains',
 'heat',
 'death',
 'imagine',
 'heat',
 'death',
 'prize',
 'carpathia',
 'represents',
 'deserves',
 'better',
 'trustees',
 'fleur',
 'sniffs',
 'conscience',
 'get',
 'better',
 'sorry',
 'know',
 'pas',
 'officers',
 'coming',
 'get',
 'jack',
 'going',
 'ask',
 'tate',
 'asking',
 'ac',
 'nobody',
 'ever',
 'told',
 'hm',
 'really',
 'tate',
 'never',
 'discussed',
 'even',
 'reported',
 'back',
 'little',
 'tete',
 'tetes',
 'acs',
 'actually',
 'tate',
 'quite',
 'one',
 'recording',
 'things',
 'happen',
 'know',
 'parents',
 'biological',
 'parents',
 'two',
 'omega',
 'scientists',
 'christian',
 'miller',
 'julia',
 'morgan',
 'true',
 'maybe',
 'shown',
 'affinity',
 'acs',
 'wonder',
 'far',
 'affinity',
 'go',
 'right',
 'let',
 'leave',
 'scheming',
 'whole',
 'time',
 'want',
 'scapegoat',
 'campaign',
 'know',
 'parents',
 'said',
 'smarmy',
 'fake',
 'liar',
 'yet',
 'grievous',
 'character',
 'flaws',
 'still',
 'human',
 'acs',
 'humans',
 'actually',
 'get',
 'away',
 'willingly',
 'even',
 'room',
 'hazardous',
 'contaminant',
 'caused',
 'virus',
 'right',
 'enough',
 'done',
 'general',
 'council',
 'decide',
 'right',
 'finally',
 'please',
 'get',
 'put',
 'end',
 'rubbish',
 'going',
 'stella',
 'berger',
 'say',
 'ac',
 'parents',
 'photos',
 'remember',
 'mean',
 'growing',
 'holidays',
 'way',
 'pas',
 'taking',
 'home',
 'safer',
 'safer',
 'crazy',
 'epidemics',
 'evoke',
 'irrational',
 'behaviour',
 'people',
 'fleur',
 'already',
 'seen',
 'least',
 'bad',
 'dream',
 'still',
 'kind',
 'aware',
 'bad',
 'dream',
 'understand',
 'go',
 'home',
 'send',
 'tate',
 'true',
 'though',
 'know',
 'part',
 'project',
 'called',
 'omega',
 'project',
 'stay',
 'leave',
 'answers',
 'need',
 'promise',
 'send',
 'tate',
 'explain',
 'everything',
 'died',
 'morning',
 'among',
 'new',
 'cases',
 'child',
 'twin',
 'sister',
 'died',
 'first',
 'c',
 'epidemic',
 'oh',
 'hoped',
 'would',
 'stay',
 'away',
 'children',
 'time',
 'fear',
 'could',
 'even',
 'worse',
 'last',
 'virus',
 'staff',
 'tell',
 'acs',
 'blame',
 'proof',
 'little',
 'girl',
 'name',
 'esperanza',
 'oh',
 'well',
 'lose',
 'going',
 'propose',
 'council',
 'given',
 'permission',
 'lead',
 'one',
 'last',
 'expedition',
 'acs',
 'operation',
 'public',
 'health',
 'fleur',
 'well',
 'starters',
 'remove',
 'citizenship',
 'mean',
 'expel',
 'forthaven',
 'deal',
 'like',
 'ac',
 'still',
 'different',
 'human',
 'jack',
 'felt',
 'human',
 'finished',
 'reading',
 'fleur',
 'morgan',
 'privileged',
 'file',
 'interesting',
 'information',
 'regarding',
 'death',
 'mitchell',
 'hoban',
 'know',
 'always',
 'suspected',
 'cass',
 'cromwell',
 'right',
 'telling',
 'telling',
 'tate',
 'covered',
 'right',
 'going',
 'send',
 'men',
 'pas',
 'find',
 'lying',
 'going',
 'take',
 'respond',
 'well',
 'threats',
 'jack',
 'first',
 'start',
 'censure',
 'motion',
 'tate',
 'sure',
 'lose',
 'stay',
 'connected',
 'best',
 'hope',
 'place',
 'right',
 'cass',
 'place',
 'take',
 'berger',
 'long',
 'notice',
 'pas',
 'speak',
 'hurry',
 'goes',
 'official',
 'detention',
 'accuse',
 'interfering',
 'accuse',
 'worry',
 'handle',
 'berger',
 'better',
 'handle',
 'anybody',
 'c',
 'could',
 'taking',
 'us',
 'one',
 'one',
 'geneticist',
 'need',
 'take',
 'ok',
 'need',
 'speak',
 'fleur',
 'first',
 'told',
 'thought',
 'idea',
 'never',
 'wanted',
 'confirmed',
 'knew',
 'omega',
 'fleur',
 'suspected',
 'though',
 'protect',
 'ac',
 'danger',
 'look',
 'prisoner',
 'really',
 'matter',
 ...]

In [70]:
'kingdom' in series[1]

False

In [71]:
'lost' in series[1]

False

In [72]:
for i in range(len(base['movie'])):
    for j in range(len(series[1])):
        if(base["movie"][i] == series[1][j]):
            if len(series[0][j][0])>0:
                base["subtitles"][i] = series[0][j][0][0]
            else:
                base["subtitles"][i] = series[0][j][0]

<ipython-input-72-a449c38300cc>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base["subtitles"][i] = series[0][j][0][0]
C:\Users\achra\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [73]:
base

,movie,genre,subtitles
0,kingdom,action,NaN
1,the invisible man,comedy,NaN
2,rick and morty,animation,NaN
3,offspring,drama,NaN
4,call the midwife,drama,"[young, seems, door, closed, though, hearts, o..."
...,...,...,...
1575,titan maximum,animation,NaN
1576,ancient impossible,documentary,NaN
1577,in the club,drama,NaN
1578,pete versus life,comedy,"[welcome, join, us, socially, inept, young, sp..."
1579,newsreaders,comedy,NaN

In [74]:
base = base.dropna()

In [75]:
base

,movie,genre,subtitles
4,call the midwife,drama,"[young, seems, door, closed, though, hearts, o..."
8,homeland,crime,"[sync, corrections, n, www, addic, ed, com, ai..."
33,hidden,drama,"[client, want, find, someone, much, know, gina..."
35,public enemies,drama,"[last, ten, years, look, risk, others, way, ro..."
38,the protector,action,"[boys, going, late, bus, chewing, fast, hey, u..."
...,...,...,...
1556,lead balloon,comedy,"[r, b, printed, bick, spleen, rick, name, rick..."
1558,the comic strip presents,comedy,"[font, color, c, c, c, programme, contains, st..."
1569,the chris rock show,comedy,"[hey, chris, rock, year, americans, die, gun, ..."
1573,top chef masters,autre,[]
1578,pete versus life,comedy,"[welcome, join, us, socially, inept, young, sp..."

In [78]:
base = base.reset_index()
base = base.drop(columns=['index'])
base

,movie,genre,subtitles
0,call the midwife,drama,"[young, seems, door, closed, though, hearts, o..."
1,homeland,crime,"[sync, corrections, n, www, addic, ed, com, ai..."
2,hidden,drama,"[client, want, find, someone, much, know, gina..."
3,public enemies,drama,"[last, ten, years, look, risk, others, way, ro..."
4,the protector,action,"[boys, going, late, bus, chewing, fast, hey, u..."
...,...,...,...
221,lead balloon,comedy,"[r, b, printed, bick, spleen, rick, name, rick..."
222,the comic strip presents,comedy,"[font, color, c, c, c, programme, contains, st..."
223,the chris rock show,comedy,"[hey, chris, rock, year, americans, die, gun, ..."
224,top chef masters,autre,[]
225,pete versus life,comedy,"[welcome, join, us, socially, inept, young, sp..."

In [81]:
for i in range(len(base['subtitles'])):
    base['subtitles'][i] = ' '.join(map(str, base['subtitles'][i] ))

In [83]:
base

,movie,genre,subtitles
0,call the midwife,drama,young seems door closed though hearts open eve...
1,homeland,crime,sync corrections n www addic ed com air naval ...
2,hidden,drama,client want find someone much know gina lot le...
3,public enemies,drama,last ten years look risk others way round incr...
4,the protector,action,boys going late bus chewing fast hey uh nichol...
...,...,...,...
221,lead balloon,comedy,r b printed bick spleen rick name rick strange...
222,the comic strip presents,comedy,font color c c c programme contains strong fon...
223,the chris rock show,comedy,hey chris rock year americans die gun related ...
224,top chef masters,autre,
225,pete versus life,comedy,welcome join us socially inept young sports wr...

In [84]:
sv.sauvegardeFichier("subtitles_genre_3",base)