In [40]:
import save as sv
import pandas as pd
from collections import Counter
import numpy as np

In [41]:
base = sv.lectureFichier("./bigbase")

In [45]:
genres = sv.lectureFichier("./base_de_donnees_genre")

In [46]:
base

                     movie                                          subtitles
0         call the midwife  young seems door closed though hearts open eve...
1                 homeland  sync corrections n www addic ed com air naval ...
2                   hidden  client want find someone much know gina lot le...
3           public enemies  last ten years look risk others way round incr...
4            the protector  boys going late bus chewing fast hey uh nichol...
...                    ...                                                ...
1058     secret girlfriend  nipple wars vanquished lord phil master oh hur...
1059          life is wild  font color anything better family trip think t...
1060      sit down shut up  honk honk high schlosers make way teacher litt...
1061  the jeff dunham show  transcript addic ed com crazymaggot addic ed c...
1062          seaquest dsv  luitenant henderson commandant op de plaats ru...

[1063 rows x 2 columns]

In [43]:
base = base.drop(columns=['genre'])

In [44]:
base

                     movie                                          subtitles
0         call the midwife  young seems door closed though hearts open eve...
1                 homeland  sync corrections n www addic ed com air naval ...
2                   hidden  client want find someone much know gina lot le...
3           public enemies  last ten years look risk others way round incr...
4            the protector  boys going late bus chewing fast hey uh nichol...
...                    ...                                                ...
1058     secret girlfriend  nipple wars vanquished lord phil master oh hur...
1059          life is wild  font color anything better family trip think t...
1060      sit down shut up  honk honk high schlosers make way teacher litt...
1061  the jeff dunham show  transcript addic ed com crazymaggot addic ed c...
1062          seaquest dsv  luitenant henderson commandant op de plaats ru...

[1063 rows x 2 columns]

In [47]:
genres

                                    movie  R Rating        Genre
0                            breaking bad       100     thriller
1                         game of thrones        99       action
2                          rick and morty        97       family
3                         stranger things        96        drama
4                                the boys        95       action
...                                   ...       ...          ...
11541                      can i catch it        10        autre
11542  kevin hart presents the next level        10       comedy
11543                      dna detectives        10  documentary
11544    tips for a happier healthier you        10        autre
11545                          esl replay        10        autre

[11546 rows x 3 columns]

In [51]:
base = base.merge(genres, how='inner', on='movie')

In [52]:
base

,movie,subtitles,R Rating,Genre
0,call the midwife,young seems door closed though hearts open eve...,78,drama
1,homeland,sync corrections n www addic ed com air naval ...,89,thriller
2,hidden,client want find someone much know gina lot le...,55,drama
3,public enemies,last ten years look risk others way round incr...,47,drama
4,the protector,boys going late bus chewing fast hey uh nichol...,68,action
...,...,...,...,...
1123,secret girlfriend,nipple wars vanquished lord phil master oh hur...,37,comedy
1124,life is wild,font color anything better family trip think t...,44,drama
1125,sit down shut up,honk honk high schlosers make way teacher litt...,41,family
1126,the jeff dunham show,transcript addic ed com crazymaggot addic ed c...,44,comedy
1127,seaquest dsv,luitenant henderson commandant op de plaats ru...,65,action

In [54]:
base=base.drop(columns=['R Rating'])
base

,movie,subtitles,Genre
0,call the midwife,young seems door closed though hearts open eve...,drama
1,homeland,sync corrections n www addic ed com air naval ...,thriller
2,hidden,client want find someone much know gina lot le...,drama
3,public enemies,last ten years look risk others way round incr...,drama
4,the protector,boys going late bus chewing fast hey uh nichol...,action
...,...,...,...
1123,secret girlfriend,nipple wars vanquished lord phil master oh hur...,comedy
1124,life is wild,font color anything better family trip think t...,drama
1125,sit down shut up,honk honk high schlosers make way teacher litt...,family
1126,the jeff dunham show,transcript addic ed com crazymaggot addic ed c...,comedy
1127,seaquest dsv,luitenant henderson commandant op de plaats ru...,action

In [57]:
len(base["Genre"].unique())

8

In [58]:
sv.sauvegardeFichier("bigbase",base)